# This file defines all the languages known to dcg and their means of identification
#
# The 'linguist' modules associates the thus-identified languages to tree-sitter parsers.
#
# [heading]s are programming language names. As they are converted into Rust enum variant names,
# they must not contain characters that can't be part of identifiers (although spaces are fine).
#
# Headings can define the following keys:
# - filenames: globs representing the filenames that correspond to this language
# - shebang: globs representing the first line (shebang or other) indicating this language
# - modeline_emacs and modeline_vim: globs for the Emacs/Vim modeline for this language
# - heuristics: globs which are matched against every line of the program to identify the language.
#
# Checks are run in this order for obvious performance reasons. If they all fail, the PlainText
# language is used and files are diffed linearily.
[agda]
filenames = ["*.agda"]

[bash]
filenames = [
	  "*.sh",
	  "*.bash",
	  ".bash_aliases",
	  ".bash_functions",
	  ".bash_history",
	  ".bash_logout",
	  ".bash_profile",
	  ".bashrc",
	  ".envrc",
	  ".login",
	  ".profile"
]
shebang = [
	"#!/bin/sh",
	"#!/bin/bash",
	"#!/usr/bin/bash",
	"#!/usr/bin/env sh",
	"#!/usr/bin/env bash"
]

[c]
filenames = ["*.c", "*.h", "*.h.in"]

[cpp]
filenames = ["*.cpp", "*.c++", "*.cc", "*.cxx", "*.cppm",
	     "*.hpp", "*.h++", "*.hh", "*.hxx", "*.txx"]

[c_sharp]
filenames = ["*.cs", "*.cake", "*.cs.pp", "*.csx"]

[css]
filenames = ["*.css"]

[erb_ejs]
filenames = ["*.ejs", "*.ect", "*.ejs.t", "*.jst", "*.erb"]

[go]
filenames = ["*.go"]

[haskell]
filenames = ["*.hs", "*.hs-boot", "*.hsc"]

[html]
filenames = ["*.html", "*.hta", "*.htm", "*.html.hl", "*.inc", "*.xht", "*.xhtml"]

[java]
filenames = ["*.java", "*.jav", "*.jsh"]

[javascript]
filenames=  [
	    "Jakefile",
	    "*.js", "*._js", "*.bones", "*.cjs", "*.es", "*.es6", "*.frag",
	    "*.gs", "*.jake", "*.javascript", "*.jsb", "*.jscad", "*.jsfl",
	    "*.jslib", "*.jsm", "*.jspre", "*.jss", "*.jsx", "*.mjs", "*.njs",
	    "*.pac", "*.sjs", "*.ssjs", "*.xsjs", "*.xsjslib"
]

[json]
filenames = [
	  ".all-contributorsrc", ".arcconfig", ".auto-changelog", ".c8rc",
	  ".htmlhintrc", ".imgbotconfig", ".nycrc", ".tern-config", ".tern-project",
	  ".watchmanconfig", "MODULE.bazel.lock", "Package.resolved", "Pipfile.lock",
	  "bun.lock", "composer.lock", "deno.lock", "flake.lock", "mcmod.info",
	  ".babelrc", ".devcontainer.json", ".eslintrc.json", ".jcsrc", ".jshintrc",
	  ".jslintrc", ".swcrc",
	  "*.json", "*.4Dform", "*.4Dproject", "*.avsc", "*.geojson", "*.gltf",
	  "*.har", "*.ice", "*.JSON-tmLanguage", "*.json.example", "*.jsonl",
	  "*.mcmeta", "*.sarif", "*.tact", "*.tfstate", "*.tfstate.backup",
	  "*.topojson", "*.webapp", "*.webmanifest", "*.yy", "*.yyp", "*.jsonc",
	  "*.code-snippets", "*.code-workspace", "*.sublime-build", "*.sublime-color-scheme",
	  "*.sublime-commands", "*.sublime-completions", "*.sublime-keymap", "*.sublime-macro",
	  "*.sublime-menu", "*.sublime-mousemap", "*.sublime_project", "*.sublime-settings",
	  "*.sublime-theme", "*.sublime-workspace", "*.sublime_metrics", "*.sublime_session",
	  "*.json5", "*.jsonld", "*.jq"
]

[julia]
filenames = ["*.jl"]

[ocaml]
filenames = ["*.ml", "*.eliom", "*.eliomi", "*.ml4", "*.mli", "*.mll", "*.mly"]

[php]
filenames = [
	  ".php", ".php_cs", ".php_cs.dist",
	  "*.php", "*.aw", "*.ctp", "*.fcgi", "*.inc", "*.php3", "*.php4", "*.php5",
	  "*.phps", "*.phpt"
]

[python]
filenames = [
	  ".gclient", "DEPS", "SConscript", "SConstruct", "wscript",
	  "*.py", "*.cgi", "*.fcgi", "*.gyp", "*.gypi", "*.lmi",
	  "*.py3", "*.pyde", "*.pyi", "*.pyp", "*.pyt", "*.pyw",
	  "*.rpy", "*.spec", "*.tac", "*.wsgi", "*.xpy"
]

[regex]
filenames = ["*.regexp", "*.regex"]

[ruby]
filenames = [
	  ".irbrc", "pryrc", ".simplecov", "Appraisals", "Berksfile", "Brewfile", "Buildfile",
	  "Capfile", "Dangerfile", "Deliverfile", "Fastfile", "Gemfile", "Guardfile", "Jarfile",
	  "Mavenfile", "Podfile", "Puppetfile", "Rakefile", "Snapfile", "Steepfile", "Thorfile",
	  "Vagrantfile", "buildfile",
	  "*.rb", "*.builder", "*.eye", "*.fcgi", "*.gemspec", "*.god", "*.jbuilder", "*.mspec",
	  "*.pluginspec", "*.podspec", "*.prawn", "*.rabl", "*.rake", "*.rbi", "*.rbuild",
	  "*.rbw", "*.rbx", "*.ru", "*.ruby", "*.spec", "*.thor", "*.watchr"
]

[rust]
filenames = ["*.rs", "*.rs.in"]

[scala]
filenames = ["*.scala", "*.kojo", "*.sbt", "*.sc"]

[typescript]
filenames = ["*.ts", "*.cts", "*.mts"]

[verilog]
filenames = ["*.v", "*.veo"]