//! This file has been auto-generated by 'build.rs'
use std::collections::BTreeMap;

#[derive(Debug, Hash, Eq, PartialEq, Copy, Clone, PartialOrd, Ord)]
pub enum Languages {
    Binary,
    PlainText,
    Rust,
}

pub static mut MODELINE_EMACS: BTreeMap<Languages, &[&str]> = BTreeMap::new();

pub static mut MODELINE_VIM: BTreeMap<Languages, &[&str]> = BTreeMap::new();

pub static mut FILENAMES: BTreeMap<Languages, &[&str]> = BTreeMap::new();
const FILENAMES_RUST: [&str; 1] = ["*.rs", ];

pub static mut SHEBANG: BTreeMap<Languages, &[&str]> = BTreeMap::new();

fn init_modeline_emacs_map() {
    unsafe {
    }
}

fn init_modeline_vim_map() {
    unsafe {
    }
}

fn init_filenames_map() {
    unsafe {
        FILENAMES.insert(Languages::Rust, &FILENAMES_RUST);
    }
}

fn init_shebang_map() {
    unsafe {
    }
}
pub(crate) fn init_all_maps() {
    init_modeline_emacs_map();
    init_modeline_vim_map();
    init_filenames_map();
    init_shebang_map();
}
